#spring:
#  application:
#    name: shifter_back
#  datasource:
#    url: jdbc:postgresql://localhost:5432/shifterdb
#    username: your_db_username
#    password: your_db_password
#    driver-class-name: org.postgresql.Driver
#  jpa:
#    database-platform: org.hibernate.dialect.PostgreSQLDialect
#    hibernate:
#      ddl-auto: update
#  doc:
#    api-docs:
#      path: /api/v1/auth/api-docs
#    swagger-ui:
#      path: /api/v1/auth/swagger.html
#
#server:
#  port: 8022
#
#backend:
#  base:
#    url: http://localhost:8080
#
#frontend:
#  url: http://localhost:3000
#
#token:
#  signing:
#    key: your-signing-key
#    expiration: 3600000
#  refresh:
#    expiration: 604800000
